### ISSUE TITLE
Why respond to IPN request with 200 first?

### ISSUE THREAD

**Issue by Fonger** [andzdroid/paypal-ipn#12]
Is it okay to delay responding to it in the end of verification?
Or reply it with other error code (400) and paypal will try to resend the IPN message?
I want to make sure that my database is available and it successfully updates the transaction database, otherwise paypal should automatically resend the IPN message later.

Is it possible? I'm sorry I can't get a clear answer from PayPal developer documents.

Example at `README.md`
```js
// Must respond to PayPal IPN request with an empty 200 first
// If using Express, uncomment the following:
// res.send(200);

var ipn = require('paypal-ipn');

ipn.verify(params, function callback(err, msg) {
  if (err) {
    console.error(err);
  } else {
    // Do stuff with original params here

    if (params.payment_status == 'Completed') {
      // Payment has been confirmed as completed
    }
  }
});
```

**Comment by brendanashworth** [comment]
PayPal requests that a 200 response is sent as soon as the IPN is delivered, and a non-200 response means that PayPal will redeliver the IPN.

If you'd like to make sure that your database is ready and all before acknowledging the request, I don't see an issue with waiting to respond as long as it doesn't take an extraordinary amount of time (re: before a human would click away). I'd say that logic makes sense, it is alright to delay the response.

**Comment by Fonger** [comment]
@brendanashworth Thanks. It works in real case.
