### ISSUE TITLE
PayPal certificate changes

### ISSUE THREAD

**Issue by bolau** [andzdroid/paypal-ipn#16]
PayPal seems to be doing an upgrade to the ssl certificates. I understand the by the end of the month, the old certificates do not work anymore:
https://devblog.paypal.com/paypal-ssl-certificate-changes/

I'm a bit confused. Does this require changes in the paypal-ipn module?
Thanks for any help
Boris

**Comment by Fonger** [comment]
There's no need to update paypal-ipn as long as your OS recognizes this certificate

**Comment by bolau** [comment]
Thanks a lot!
